baseURL = ""
languageCode = "en-us"
title = "A Hugo theme for creating Webslides.js presentations"
disableKinds = [ "sitemap", "RSS" ]
theme = "hugo-webslides"
themesDir = "themes"
tags = [ "slide", "presentation", "responsive", "landing page" ]
features = [ "webslides.js", "pre-made template", "shortcodes" ]
publishDir = "public"

[params]
author = "RCJacH"
homepage = "RCJacH.github.io"

  [params.webslides]
  banner = false
  slideshow = true
  vertical = false
  autoslide = false
  changeOnClick = false
  disableLoop = false
  minWheelDelta = 40
  disableNavigateOnScroll = false
  scrollWait = 450
  slideOffset = 50
  hideIndex = false

[markup]
defaultMarkdownHandler = "blackfriday"

[markup.goldmark.renderer]
unsafe = true
